//// <auto-generated />
//using System;
//using DAB2_2.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace DAB2_3.Migrations
//{
//    [DbContext(typeof(MyDbContext))]
//    partial class MyDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("ProductVersion", "5.0.12")
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("DAB2_2.Models.Address", b =>
//                {
//                    b.Property<int>("AddressId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int>("Number")
//                        .HasColumnType("int");

//                    b.Property<string>("Street")
//                        .IsRequired()
//                        .HasMaxLength(64)
//                        .HasColumnType("nvarchar(64)");

//                    b.Property<int>("Zip")
//                        .HasColumnType("int");

//                    b.HasKey("AddressId");

//                    b.ToTable("Addresses");
//                });

//            modelBuilder.Entity("DAB2_2.Models.Booking", b =>
//                {
//                    b.Property<int>("SocietyId")
//                        .HasColumnType("int");

//                    b.Property<int>("RoomId")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("TimeStart")
//                        .HasColumnType("datetime2");

//                    b.HasKey("SocietyId", "RoomId", "TimeStart");

//                    b.HasIndex("RoomId");

//                    b.ToTable("Bookings");
//                });

//            modelBuilder.Entity("DAB2_2.Models.Person", b =>
//                {
//                    b.Property<int>("Cpr")
//                        .HasColumnType("int");

//                    b.Property<int>("AddressId")
//                        .HasColumnType("int");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasMaxLength(64)
//                        .HasColumnType("nvarchar(64)");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasMaxLength(64)
//                        .HasColumnType("nvarchar(64)");

//                    b.Property<int?>("License")
//                        .HasColumnType("int");

//                    b.Property<int?>("Phonenumber")
//                        .HasColumnType("int");

//                    b.HasKey("Cpr");

//                    b.HasIndex("AddressId");

//                    b.ToTable("Persons");
//                });

//            modelBuilder.Entity("DAB2_2.Models.Room", b =>
//                {
//                    b.Property<int>("RoomId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int>("AddressId")
//                        .HasColumnType("int");

//                    b.Property<int>("ClosingHour")
//                        .HasColumnType("int");

//                    b.Property<int>("MaximumOccupancy")
//                        .HasColumnType("int");

//                    b.Property<int>("OpeningHour")
//                        .HasColumnType("int");

//                    b.Property<string>("RoomName")
//                        .IsRequired()
//                        .HasMaxLength(64)
//                        .HasColumnType("nvarchar(64)");

//                    b.HasKey("RoomId");

//                    b.HasIndex("AddressId");

//                    b.ToTable("Rooms");
//                });

//            modelBuilder.Entity("DAB2_2.Models.Society", b =>
//                {
//                    b.Property<int>("Cvr")
//                        .HasColumnType("int");

//                    b.Property<string>("Activity")
//                        .IsRequired()
//                        .HasMaxLength(64)
//                        .HasColumnType("nvarchar(64)");

//                    b.Property<int>("AddressId")
//                        .HasColumnType("int");

//                    b.Property<int?>("ChairmanId")
//                        .HasColumnType("int");

//                    b.Property<int?>("KeyholderId")
//                        .HasColumnType("int");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(64)
//                        .HasColumnType("nvarchar(64)");

//                    b.HasKey("Cvr");

//                    b.HasIndex("AddressId");

//                    b.HasIndex("ChairmanId");

//                    b.HasIndex("KeyholderId");

//                    b.ToTable("Societies");
//                });

//            modelBuilder.Entity("DAB2_3.Models.Code", b =>
//                {
//                    b.Property<int>("Pin")
//                        .HasColumnType("int");

//                    b.Property<int>("RoomId")
//                        .HasColumnType("int");

//                    b.HasKey("Pin", "RoomId");

//                    b.HasIndex("RoomId");

//                    b.ToTable("Codes");
//                });

//            modelBuilder.Entity("DAB2_3.Models.Key", b =>
//                {
//                    b.Property<int>("KeyId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int>("AddressId")
//                        .HasColumnType("int");

//                    b.Property<int>("RoomId")
//                        .HasColumnType("int");

//                    b.HasKey("KeyId");

//                    b.HasIndex("AddressId");

//                    b.HasIndex("RoomId")
//                        .IsUnique();

//                    b.ToTable("Keys");
//                });

//            modelBuilder.Entity("DAB2_2.Models.Booking", b =>
//                {
//                    b.HasOne("DAB2_2.Models.Room", "Room")
//                        .WithMany("BookingList")
//                        .HasForeignKey("RoomId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("DAB2_2.Models.Society", "Society")
//                        .WithMany("Bookings")
//                        .HasForeignKey("SocietyId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Room");

//                    b.Navigation("Society");
//                });

//            modelBuilder.Entity("DAB2_2.Models.Person", b =>
//                {
//                    b.HasOne("DAB2_2.Models.Address", "Address")
//                        .WithMany()
//                        .HasForeignKey("AddressId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Address");
//                });

//            modelBuilder.Entity("DAB2_2.Models.Room", b =>
//                {
//                    b.HasOne("DAB2_2.Models.Address", "Address")
//                        .WithMany()
//                        .HasForeignKey("AddressId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Address");
//                });

//            modelBuilder.Entity("DAB2_2.Models.Society", b =>
//                {
//                    b.HasOne("DAB2_2.Models.Address", "Address")
//                        .WithMany()
//                        .HasForeignKey("AddressId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("DAB2_2.Models.Person", "Chairman")
//                        .WithMany()
//                        .HasForeignKey("ChairmanId");

//                    b.HasOne("DAB2_2.Models.Person", "Keyholder")
//                        .WithMany()
//                        .HasForeignKey("KeyholderId");

//                    b.Navigation("Address");

//                    b.Navigation("Chairman");

//                    b.Navigation("Keyholder");
//                });

//            modelBuilder.Entity("DAB2_3.Models.Code", b =>
//                {
//                    b.HasOne("DAB2_2.Models.Room", "Room")
//                        .WithMany("Codes")
//                        .HasForeignKey("RoomId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Room");
//                });

//            modelBuilder.Entity("DAB2_3.Models.Key", b =>
//                {
//                    b.HasOne("DAB2_2.Models.Address", "Address")
//                        .WithMany()
//                        .HasForeignKey("AddressId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("DAB2_2.Models.Room", "Room")
//                        .WithOne("Key")
//                        .HasForeignKey("DAB2_3.Models.Key", "RoomId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Address");

//                    b.Navigation("Room");
//                });

//            modelBuilder.Entity("DAB2_2.Models.Room", b =>
//                {
//                    b.Navigation("BookingList");

//                    b.Navigation("Codes");

//                    b.Navigation("Key");
//                });

//            modelBuilder.Entity("DAB2_2.Models.Society", b =>
//                {
//                    b.Navigation("Bookings");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
